name: baseproject_flutter
description: "A flexible and robust Flutter base project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # state management
  flutter_riverpod: ^3.0.3
  riverpod_annotation: ^3.0.3

  # http client
  dio: ^5.9.0
  flutter_pretty_dio_logger: ^3.0.0

  # local data
  encrypt_shared_preferences: ^0.9.10

  # dependency injection
  get_it: ^8.2.0
  injectable: ^2.5.2

  # ui
  flutter_screenutil: ^5.9.3
  mask_text_input_formatter: ^2.9.0
  pattern_formatter: ^4.0.1
  fluttertoast: ^9.0.0
  photo_view: ^0.15.0

  # utils
  intl: ^0.20.2
  package_info_plus: ^9.0.1
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  permission_handler: ^12.0.3
  samseer: ^0.4.0
  flutter_local_notifications: ^22.0.1

dependency_overrides:
  intl: ^0.20.2
  test: ^1.25.8
  analyzer: ^7.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_flavorizr: ^2.2.3

  # code generator
  build_runner: ^2.5.4
  injectable_generator: ^2.6.2
  riverpod_generator: ^3.0.3
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/image/
    - assets/translation/
    - assets/font/

  fonts:
    - family: BeVietnamPro
      fonts:
        - asset: assets/font/BeVietnamPro-Light.ttf
          weight: 300
        - asset: assets/font/BeVietnamPro-Regular.ttf
          weight: 400
        - asset: assets/font/BeVietnamPro-Medium.ttf
          weight: 500
        - asset: assets/font/BeVietnamPro-SemiBold.ttf
          weight: 600
        - asset: assets/font/BeVietnamPro-Bold.ttf
          weight: 700

flavorizr:
  ide: "vscode"
  app:
    android:
      flavorDimensions: "flavor-type"

  flavors:
    dev:
      app:
        name: "Base App Dev"
      android:
        applicationId: "com.example.baseproject.dev"
      ios:
        bundleId: "com.example.baseproject.dev"
    staging:
      app:
        name: "Base App Stg"
      android:
        applicationId: "com.example.baseproject.staging"
      ios:
        bundleId: "com.example.baseproject.staging"
    prod:
      app:
        name: "Base App"
      android:
        applicationId: "com.example.baseproject"
      ios:
        bundleId: "com.example.baseproject"
