import java.util.Properties
import java.io.FileInputStream

plugins {
    id("com.android.application")
    // The Flutter Gradle Plugin handles Kotlin compilation via built-in Kotlin.
    id("dev.flutter.flutter-gradle-plugin")
}

// Load key.properties safely if it exists
val keystoreProperties = Properties()
val keystorePropertiesFile = rootProject.file("key.properties")
val hasKeystore = keystorePropertiesFile.exists() && keystorePropertiesFile.isFile
if (hasKeystore) {
    keystoreProperties.load(FileInputStream(keystorePropertiesFile))
}

android {
    namespace = "com.mapid"
    compileSdk = flutter.compileSdkVersion
    ndkVersion = flutter.ndkVersion

    compileOptions {
        isCoreLibraryDesugaringEnabled = true
        sourceCompatibility = JavaVersion.VERSION_11
        targetCompatibility = JavaVersion.VERSION_11
    }

    kotlinOptions {
        jvmTarget = JavaVersion.VERSION_11.toString()
    }

    defaultConfig {
        applicationId = "com.mapid"
        minSdk = flutter.minSdkVersion
        targetSdk = flutter.targetSdkVersion
        versionCode = flutter.versionCode
        versionName = flutter.versionName
    }

    signingConfigs {
        create("release") {
            val keyAliasProp = keystoreProperties.getProperty("keyAlias")
            val keyPasswordProp = keystoreProperties.getProperty("keyPassword")
            val storeFileProp = keystoreProperties.getProperty("storeFile")
            val storePasswordProp = keystoreProperties.getProperty("storePassword")

            if (hasKeystore &&
                !keyAliasProp.isNullOrEmpty() &&
                !keyPasswordProp.isNullOrEmpty() &&
                !storeFileProp.isNullOrEmpty() &&
                !storePasswordProp.isNullOrEmpty()
            ) {
                keyAlias = keyAliasProp
                keyPassword = keyPasswordProp
                val keyFile = if (rootProject.file(storeFileProp).exists()) {
                    rootProject.file(storeFileProp)
                } else {
                    file(storeFileProp)
                }
                storeFile = keyFile
                storePassword = storePasswordProp
            } else {
                // Fallback to debug signing config when key.properties is absent (e.g. during development/cloning)
                val debugSigning = getByName("debug")
                keyAlias = debugSigning.keyAlias
                keyPassword = debugSigning.keyPassword
                storeFile = debugSigning.storeFile
                storePassword = debugSigning.storePassword
            }
        }
    }

    buildTypes {
        getByName("release") {
            val releaseSigning = signingConfigs.getByName("release")
            signingConfig = if (releaseSigning.storeFile?.exists() == true) {
                releaseSigning
            } else {
                signingConfigs.getByName("debug")
            }
            isMinifyEnabled = false
            isShrinkResources = false
            proguardFiles(
                getDefaultProguardFile("proguard-android-optimize.txt"),
                "proguard-rules.pro"
            )
        }
    }
}

dependencies {
    coreLibraryDesugaring("com.android.tools:desugar_jdk_libs:2.1.4")
}

flutter {
    source = "../.."
}

tasks.withType<JavaCompile>().configureEach {
    options.compilerArgs.add("-Xlint:-options")
}

// ----- BEGIN flavorDimensions (autogenerated by flutter_flavorizr) -----
apply { from("flavorizr.gradle.kts") }
// ----- END flavorDimensions (autogenerated by flutter_flavorizr) -----